"""Shared helpers for Readwise skills."""

from .auth import get_reader_token, get_readwise_token
from .formatting import print_result, render_highlights, render_output, select_fields
from .http import RateLimitInfo, request_with_backoff
from .models import (
    Book,
    BookListParams,
    DailyReviewParams,
    DailyReviewResponse,
    DeleteResult,
    Document,
    DocumentCreatePayload,
    DocumentListParams,
    DocumentPullParams,
    DocumentSaveResponse,
    DocumentUpdatePayload,
    DryRunResult,
    Highlight,
    HighlightCreatePayload,
    HighlightListParams,
    HighlightUpdatePayload,
    TokenValidationResult,
)
from .utils import (
    build_location_payload,
    build_tags,
    format_inline_tags,
    hoist_global_options,
    parse_iso_datetime,
    parse_tags,
    resolve_highlight_text,
)

__all__ = [
    "get_readwise_token",
    "get_reader_token",
    "request_with_backoff",
    "RateLimitInfo",
    "print_result",
    "render_highlights",
    "render_output",
    "select_fields",
    "build_tags",
    "format_inline_tags",
    "hoist_global_options",
    "parse_iso_datetime",
    "parse_tags",
    "resolve_highlight_text",
    "build_location_payload",
    "Book",
    "BookListParams",
    "DailyReviewParams",
    "DailyReviewResponse",
    "DeleteResult",
    "Document",
    "DocumentCreatePayload",
    "DocumentListParams",
    "DocumentPullParams",
    "DocumentSaveResponse",
    "DocumentUpdatePayload",
    "DryRunResult",
    "Highlight",
    "HighlightCreatePayload",
    "HighlightListParams",
    "HighlightUpdatePayload",
    "TokenValidationResult",
]
